using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Web;
using System.Web.SessionState;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.HtmlControls;
using System.Web.Mail;

namespace contacts.site
{
	/// <summary>
	/// Summary description for contactkk.
	/// </summary>
	public class contactkk : System.Web.UI.Page
	{
		protected System.Web.UI.WebControls.Label acknowledgementLbl;
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		protected System.Web.UI.WebControls.TextBox detailTxt;
		protected System.Web.UI.WebControls.Label detailLbl;
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		protected System.Web.UI.WebControls.TextBox emailTxt;
		protected System.Web.UI.WebControls.Label emailLbl;
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		protected System.Web.UI.WebControls.TextBox nameTxt;
		protected System.Web.UI.WebControls.Label nameLbl;
		protected System.Web.UI.WebControls.Button sendBtn;
		protected System.Web.UI.HtmlControls.HtmlTable tbl;
	
		private void Page_Load(object sender, System.EventArgs e)
		{
			// Put user code to initialize the page here
		}

		#region Web Form Designer generated code
		override protected void OnInit(EventArgs e)
		{
			//
			// CODEGEN: This call is required by the ASP.NET Web Form Designer.
			//
			InitializeComponent();
			base.OnInit(e);
		}
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{    
			this.sendBtn.Click += new System.EventHandler(this.sendBtn_Click);
			this.Load += new System.EventHandler(this.Page_Load);

		}
		#endregion
		private void sendEmail(string email, string body, string subject, string from)
		{
			MailMessage oMessage = new MailMessage();
			oMessage.To = email;
			oMessage.From = from;
			oMessage.Subject = subject;
			oMessage.Body = body;
			oMessage.BodyFormat = MailFormat.Html;
			oMessage.Fields["http://schemas.microsoft.com/cdo/configuration/sendusing"] = 2;
			oMessage.Fields["http://schemas.microsoft.com/cdo/configuration/smtpserver"] = "mail.brinkster.net";
			oMessage.Fields["http://schemas.microsoft.com/cdo/configuration/sendusername"] = "minhajkk@brinkster.net";
			oMessage.Fields["http://schemas.microsoft.com/cdo/configuration/sendpassword"] = "brinkster";
			oMessage.Fields["http://schemas.microsoft.com/cdo/configuration/smtpauthenticate"] = 1;
			System.Web.Mail.SmtpMail.SmtpServer = "mail.brinkster.net";
			System.Web.Mail.SmtpMail.Send(oMessage);


//			SmtpMail.SmtpServer = "mail.brinkster.net";
//			MailMessage objMail = new MailMessage();
//			objMail.Fields.Add("http://schemas.microsoft.com/cdo/configuration/smtsperver", "mail.brinkster.net");
//			objMail.Fields.Add("http://schemas.microsoft.com/cdo/configuration/smtpserverport", 25);
//			objMail.Fields.Add("http://schemas.microsoft.com/cdo/configuration/sendusing", 2);
//			objMail.From = from;
//			objMail.To = email;
//			objMail.Subject = subject;
//			objMail.Bcc = "suny_kk@hotmail.com";
//			objMail.Cc = "suny_kk@yahoo.co.in";
//			objMail.BodyFormat = MailFormat.Html;
//			objMail.Body = body;
//			SmtpMail.SmtpServer = "mail.brinkster.net";
//			SmtpMail.Send(objMail);
		}

		private void sendBtn_Click(object sender, System.EventArgs e)
		{
			try
			{
				string msg ="<font face='arial' size='3'>Name :"+nameTxt.Text.ToString()+
					"<br/><br/> Message Details: "+
					detailTxt.Text.ToString() +"</font>";

				sendEmail("minhajkk@brinkster.net",
					msg,
					"Vsitors Inquiry at minhajkk.brinksert.net",
					emailTxt.Text.ToString()
					);
				//Response.Write(msg);
				tbl.Visible = false;
				acknowledgementLbl.Visible = true;
				acknowledgementLbl.Text = ":) Your feedback has been sent to webmaster. we will contact you soon THANKS.";
			}
			catch (Exception exp)
			{
				tbl.Visible = false; 
				acknowledgementLbl.Visible = true; 
				acknowledgementLbl.Text = exp.Message.ToString();
			}
			//Response.Write("this is generated by codebehind file in C# at brinkster free domain");
		}
	}
}